### ISSUE TITLE
RequestAdditionalTime implementation request

### ISSUE THREAD

**Issue by GioviQ** [RobThree/DebuggableSelfInstallingService#1]
Please add support to https://msdn.microsoft.com/en-us/library/system.serviceprocess.servicebase.requestadditionaltime(v=vs.110).aspx

**Comment by RobThree** [comment]
Uh, from the documentation:

> The RequestAdditionalTime method is intended to be called by the overridden OnContinue, OnPause, OnStart, or OnStop methods to request additional time for a pending operation, to prevent the Service Control Manager (SCM) from marking the service as not responding. If the pending operation is not a continue, pause, start, or stop, an InvalidOperationException is thrown.

You should just call `RequestAdditionalTime` in any of the  `OnContinue`, `OnPause`, `OnStart`, or `OnStop` methods? Or did I not understand your question?

**Comment by GioviQ** [comment]
Yes, I should call RequestAdditionalTime in my case in OnStart and OnStop.
Thanks

**Comment by RobThree** [comment]
👍

**Comment by GioviQ** [comment]
Closed means you have just done?

**Comment by RobThree** [comment]
Closed means it's done / no action required / end of issue 😉

**Comment by GioviQ** [comment]
So I have to do it by myself, this is the meaning...

**Comment by RobThree** [comment]
Uh, yes?
I don't see what you'd want me to do? This is very specific on a per-project basis and not something to implement in this template. All you have to do is call the method whenever you see fit in whichever overriden method you see fit.
